# Generated by Django 5.1.2 on 2024-10-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=500)),
                ('certification_category', models.CharField(max_length=250)),
                ('certification_keyword', models.TextField()),
                ('certification_platform', models.CharField(max_length=250)),
                ('certification_img', models.CharField(max_length=300)),
                ('certification_link', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Certifications',
            },
        ),
    ]
