# Generated by Django 5.1.2 on 2024-10-24 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Plataformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Plataformas',
            },
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='Universidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('region_universidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Universidades', to='topeducation.regiones')),
            ],
            options={
                'db_table': 'Universidades',
            },
        ),
        migrations.CreateModel(
            name='Certificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('palabra_clave_certificacion', models.TextField()),
                ('url_certificacion_original', models.CharField(default='Null', max_length=300)),
                ('metadescripcion_certificacion', models.TextField(default='NONE')),
                ('instructores_certificacion', models.TextField(default='NONE')),
                ('nivel_certificacion', models.TextField(default='NONE')),
                ('tiempo_certificacion', models.TextField(default='NONE')),
                ('lenguaje_certificacion', models.TextField(default='NONE')),
                ('aprendizaje_certificacion', models.TextField(default='NONE')),
                ('habilidades_certificacion', models.TextField(default='NONE')),
                ('experiencia_certificacion', models.TextField(default='NONE')),
                ('contenido_certificacion', models.TextField(default='NONE')),
                ('modulos_certificacion', models.TextField(default='NONE')),
                ('testimonios_certificacion', models.TextField(default='NONE')),
                ('empresa_certificacion', models.CharField(blank=True, default='No Aplica', max_length=300)),
                ('url_imagen_universidad_certificacion', models.TextField(blank=True)),
                ('url_imagen_plataforma_certificacion', models.TextField(blank=True)),
                ('plataforma_certificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plataforma_certificacion', to='topeducation.plataformas')),
                ('region_universidad_certificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_region', to='topeducation.regiones')),
                ('tema_certificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tema_certificacion', to='topeducation.temas')),
                ('universidad_certificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_university', to='topeducation.universidades')),
            ],
            options={
                'db_table': 'Certificaciones',
            },
        ),
    ]
