# Generated by Django 5.1.2 on 2024-10-24 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='habilidades',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='plataformas',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='regiones',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='temas',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='universidades',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='plataforma_certificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topeducation.plataformas'),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='region_universidad_certificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topeducation.regiones'),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='tema_certificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topeducation.temas'),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='universidad_certificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topeducation.universidades'),
        ),
        migrations.AlterField(
            model_name='universidades',
            name='region_universidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topeducation.regiones'),
        ),
    ]
