# Generated by Django 5.2.1 on 2025-07-03 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(max_length=255)),
                ('auto_img', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'autores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_blog', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(default='default-slug', max_length=500, verbose_name='Slug')),
                ('fecha_redaccion_blog', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('miniatura_blog', models.CharField(max_length=255, null=True, verbose_name='Imagen')),
                ('palabra_clave_blog', models.CharField(max_length=255, verbose_name='Palabra clave')),
                ('metadescripcion_blog', models.TextField(null=True, verbose_name='Metadescripción')),
                ('objetivo_blog', models.TextField(null=True, verbose_name='Objetivo')),
                ('contenido', models.TextField(blank=True, verbose_name='Contenido')),
                ('url_img_cta', models.CharField(max_length=255, null=True, verbose_name='Imagen de cita')),
            ],
            options={
                'db_table': 'blogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria_blog', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categorias_blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Original',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('biog', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='empresas',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='habilidades',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='plataformas',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='universidades',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='certificaciones',
            name='region_universidad_certificacion',
        ),
        migrations.RemoveField(
            model_name='certificaciones',
            name='url_imagen_plataforma_certificacion',
        ),
        migrations.RemoveField(
            model_name='certificaciones',
            name='url_imagen_universidad_certificacion',
        ),
        migrations.RemoveField(
            model_name='regiones',
            name='name',
        ),
        migrations.RemoveField(
            model_name='temas',
            name='name',
        ),
        migrations.AddField(
            model_name='certificaciones',
            name='cert_top',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='certificaciones',
            name='fecha_creado_cert',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificaciones',
            name='imagen_final',
            field=models.CharField(default='Null', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificaciones',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=500),
        ),
        migrations.AddField(
            model_name='certificaciones',
            name='video_certificacion',
            field=models.CharField(default='Null', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='empr_est',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='empr_ico',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='empr_img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plataformas',
            name='plat_ico',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plataformas',
            name='plat_img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regiones',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temas',
            name='nombre',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='temas',
            name='tem_col',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='temas',
            name='tem_img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='temas',
            name='tem_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='universidades',
            name='univ_est',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='universidades',
            name='univ_fla',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='universidades',
            name='univ_ico',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='universidades',
            name='univ_img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='contenido_certificacion',
            field=models.TextField(blank=True, default='NONE', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='empresa_certificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topeducation.empresas'),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='lenguaje_certificacion',
            field=models.CharField(default='NONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='nivel_certificacion',
            field=models.CharField(default='NONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='plataforma_certificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topeducation.plataformas'),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='tema_certificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topeducation.temas'),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='tiempo_certificacion',
            field=models.CharField(default='NONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='universidad_certificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topeducation.universidades'),
        ),
        migrations.AlterField(
            model_name='universidades',
            name='region_universidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universidades', to='topeducation.regiones'),
        ),
        migrations.CreateModel(
            name='OriginalCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('history', models.TextField()),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topeducation.certificaciones')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='topeducation.original')),
            ],
            options={
                'unique_together': {('original', 'certification')},
            },
        ),
    ]
