# Generated by Django 5.1.2 on 2024-10-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0002_companies_regions_topics_rename_category_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Plataformas',
            },
        ),
    ]
