# Generated by Django 5.2.1 on 2025-11-19 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0002_autor_blog_categoriablog_original_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rankings/images/', verbose_name='Imagen')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('universidad', 'Universidad'), ('empresa', 'Empresa')], max_length=50)),
                ('estado', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], max_length=50)),
            ],
            options={
                'db_table': 'Ranking',
            },
        ),
        migrations.CreateModel(
            name='WhiteLabelBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la marca')),
                ('slug', models.SlugField(help_text='Se usará en la URL, ej: https://top.education/marca-blanca/<slug>/', max_length=150, unique=True, verbose_name='Slug de la marca')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marca_blanca/logos/', verbose_name='Logo de la marca')),
                ('primary_color', models.CharField(default='#0F090B', help_text='Formato HEX, ej: #FF0000', max_length=7, verbose_name='Color principal')),
                ('secondary_color', models.CharField(default='#F6F4EF', help_text='Formato HEX, ej: #00FF00', max_length=7, verbose_name='Color secundario')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=8, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Marca blanca',
                'verbose_name_plural': 'Marcas blancas',
            },
        ),
        migrations.AlterModelOptions(
            name='original',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='originalcertification',
            name='history',
        ),
        migrations.AddField(
            model_name='empresas',
            name='empr_top',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Ranking global'),
        ),
        migrations.AddField(
            model_name='originalcertification',
            name='fondo',
            field=models.ImageField(blank=True, null=True, upload_to='originals/autores/history/', verbose_name='Fondo'),
        ),
        migrations.AddField(
            model_name='originalcertification',
            name='hist',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Historia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='originalcertification',
            name='posicion',
            field=models.PositiveIntegerField(default=django.utils.timezone.now, verbose_name='Posición'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temas',
            name='tem_est',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='universidades',
            name='univ_top',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Ranking global'),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='cert_top',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Ranking global'),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='empresa_certificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificaciones', to='topeducation.empresas'),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='imagen_final',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='universidad_certificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificaciones', to='topeducation.universidades'),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='video_certificacion',
            field=models.CharField(blank=True, default='Null', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='empr_est',
            field=models.CharField(max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='empr_ico',
            field=models.CharField(max_length=100, null=True, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='empr_img',
            field=models.CharField(max_length=200, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nombre',
            field=models.CharField(max_length=500, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='originalcertification',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topeducation.certificaciones', verbose_name='Certificación'),
        ),
        migrations.AlterField(
            model_name='originalcertification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='universidades',
            name='nombre',
            field=models.CharField(max_length=500, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='universidades',
            name='univ_est',
            field=models.CharField(max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='universidades',
            name='univ_fla',
            field=models.CharField(max_length=200, null=True, verbose_name='Bandera'),
        ),
        migrations.AlterField(
            model_name='universidades',
            name='univ_ico',
            field=models.CharField(max_length=100, null=True, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='universidades',
            name='univ_img',
            field=models.CharField(max_length=200, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterModelTable(
            name='originalcertification',
            table='Original_certification',
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveIntegerField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topeducation.empresas')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='topeducation.ranking')),
                ('universidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topeducation.universidades')),
            ],
            options={
                'db_table': 'Ranking_entry',
                'ordering': ['posicion'],
                'unique_together': {('ranking', 'posicion')},
            },
        ),
        migrations.CreateModel(
            name='BrandPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: About us, Explora, Los más top...', max_length=100, verbose_name='Nombre del permiso')),
                ('section_key', models.CharField(choices=[('about', 'Sección About us'), ('explore', 'Sección Explora'), ('top', 'Sección Los más top'), ('blog', 'Sección Blog'), ('skills', 'Sección Habilidades'), ('topics', 'Sección Temas')], help_text='Identificador técnico de la sección.', max_length=20, verbose_name='Clave de sección')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('order', models.PositiveIntegerField(default=0, help_text='Posición de la sección en el front.', verbose_name='Orden')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='topeducation.whitelabelbrand', verbose_name='Marca blanca')),
            ],
            options={
                'verbose_name': 'Permiso de marca',
                'verbose_name_plural': 'Permisos de marca',
                'ordering': ['order'],
                'unique_together': {('brand', 'section_key')},
            },
        ),
    ]
