# Generated by Django 5.1.2 on 2024-10-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0002_rename_name_empresas_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaciones',
            name='empresa_certificacion',
            field=models.CharField(blank=True, default='No Aplica', max_length=300, null=True),
        ),
    ]
