# Generated by Django 5.1.2 on 2024-10-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0003_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certification_enterprise',
            field=models.CharField(default='No Aplica', max_length=300),
        ),
    ]
