# Generated by Django 5.1.2 on 2024-10-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0004_alter_certificaciones_url_imagen_plataforma_certificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaciones',
            name='url_imagen_empresa_certificacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
