# Generated by Django 5.1.2 on 2024-10-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0004_certification_certification_enterprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='certification_img',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certification_link',
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_content',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_experience',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_instructors',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_language',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_learnings',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_level',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_metadescription',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_modules',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_skills',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_testimonials',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_time',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_topic', to='topeducation.topics'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_university', to='topeducation.universities'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_university_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_university_region', to='topeducation.regions'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_url_original',
            field=models.CharField(default='Null', max_length=300),
        ),
        migrations.AddField(
            model_name='universities',
            name='university_url_img',
            field=models.ImageField(blank=True, upload_to='platform_imgs/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certification_enterprise',
            field=models.CharField(blank=True, default='No Aplica', max_length=300),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certification_platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_platform', to='topeducation.platforms'),
        ),
    ]
