# Generated by Django 5.1.2 on 2024-10-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0005_certificaciones_url_imagen_empresa_certificacion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certificaciones',
            table=None,
        ),
    ]
