# Generated by Django 5.1.2 on 2024-10-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0006_alter_certificaciones_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaciones',
            name='imagen_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='certificaciones',
            table='Certificaciones',
        ),
    ]
