# Generated by Django 5.1.2 on 2024-10-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0006_remove_universities_university_url_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='company_img',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='platforms',
            name='platform_img',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='university_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
