# Generated by Django 5.1.2 on 2025-01-10 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0009_alter_autor_table_alter_blog_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql = "SELECT 1",
            reverse_sql="SELECT 1"
        ),
    ]
