# Generated by Django 5.1.2 on 2024-10-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0010_rename_certification_university_url_img_certification_certification_platform_url_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certification_university_url_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
