# Generated by Django 5.1.5 on 2025-02-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0011_certificaciones_fecha_creado_cert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaciones',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=500),
        ),
    ]
