# Generated by Django 5.1.2 on 2024-10-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0011_certification_certification_university_url_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='certification_category',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certifition_platform_img',
        ),
    ]
