# Generated by Django 5.1.5 on 2025-02-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0012_certificaciones_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-fecha_blog_redaccion'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='fecha_blog_redacccion',
            new_name='fecha_blog_redaccion',
        ),
    ]
