# Generated by Django 5.1.5 on 2025-02-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topeducation', '0013_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=500),
        ),
    ]
